### PR TITLE
Changed references of 'bitcoin' to 'bytecoin'

### PR DESCRIPTION
**Pull request by lucasjones**
Compiled successfully on Ubuntu 13.04 64bit.

### CODE REVIEW

**Comment by ahmedbodi** [comment]
so it compiles well?

**Comment by lucasjones** [comment]
It compiled on my machine, and the build system is compiling it now if you want to see.
http://bytecoin.us.to:8080/job/ahmedbodi_Bytecoin-MM_m0.8.1_merged/

The Buildbot should post once it has been compiled :)

**Comment by ahmedbodi** [comment]
right okay i cant get it to compile. although im not sure if i pulled properly

**Comment by lucasjones** [comment]
What platform are you using, and what error are you getting?

**Comment by ahmedbodi** [comment]
debian 64bit same error as before: http://pastebin.com/reeBCrFr ill try out your build when its downloaded

**Comment by ahmedbodi** [comment]
actually i was trying the QT ill try the daemon now

**Comment by ahmedbodi** [comment]
i get this when compiling the daemon:
zeromq.cpp: In function ‘int zeromq_newblock(int)’:
zeromq.cpp:60:52: error: ‘zmq_sendmsg’ was not declared in this scope

**Comment by lucasjones** [comment]
Do you have zeromq installed?
http://www.zeromq.org/

**Comment by ahmedbodi** [comment]
i think so
how did you install it?

**Comment by lucasjones** [comment]
The build instructions for 'UNIX-like systems' at http://www.zeromq.org/intro:get-the-software should work

**Comment by ahmedbodi** [comment]
same error

**Comment by lucasjones** [comment]
Can you make sure that you have the 3.1+ release, not 2.2?

**Comment by ahmedbodi** [comment]
ive got 3.2.3

**Comment by ahmedbodi** [comment]
could you try compiling the qt

**Comment by lucasjones** [comment]
Okay, I'll try to compile it now

**Comment by ahmedbodi** [comment]
what grep command do you run to change the names?

**Comment by lucasjones** [comment]
It's a script I wrote to rename bitcoin (~8 commands).
QT didn't compile for me, I got the same error as you.
I have to leave now. I'll check out the errors tomorrow if you haven't by then.

**Comment by ahmedbodi** [comment]
sure no probs

**Comment by lucasjones** [comment]
By the way, I've stopped Jenkins as the server seems to have a lot of errors (e.g. it doesn't even let project configurations be edited).

**Comment by ahmedbodi** [comment]
okay, when you get the chance could you email me that script to ahmed_bodi@msn.com i want to try it out on another copy of the coin from fresh and it'd save me from having to get you to do it over and over again

**Pull request merged**
